### ISSUE TITLE
Update can cause an extraneous slice to be created

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/inago#213]
@xh3b4sd and I had a case today where we had two slices running, and an update with min-alive=1, max-growth=0 presented an update like so:
1. [339, 591]
2. [591]
3. [0a0, 591, 72e]
4. [0a0, 72e]

It would seem that at 3, 2 additional slices were made. With max-growth=0, we would expect only one slice to have been created at this point.

**Comment by Nesurion** [comment]
so @JosephSalisbury and I paired on this and looked at the debug logs. What we found is that:
- From step 2 to step 3, only one slice should be added, but it adds two
- this might be due to the way we calculate the number of slices we are allowed to add
- a race condition in the `addInProgress` counter is unlikely (we checked for that)

we need to dig deeper into this tomorrow
