### ISSUE TITLE
Add support for creating group instances and group slices

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/inago#6]
We want to be able to create a group instance, running on the fleet cluster.

e.g:

```
$ ls example-group/
example-group-unit-1.service example-group-unit-2.service
$ formica create example-group
$ fleetctl list-units
example-group-unit-1.service example-group-unit-2.service
```

This should submit all the unit files in the group to the cluster.

We also want to support creating group slices:
e.g:

```
$ ls example-group-2/
example-group-2-unit-1@.service
$ formica create example-group-2@1 example-group-2@2
$ fleetctl list-units
example-group-2-unit-1@1.service example-group-2-unit-1@2.service
```

The units do not need to be started, at this point - just submitted.

**Comment by JosephSalisbury** [comment]
ping @zeisss @xh3b4sd

**Comment by xh3b4sd** [comment]
We agreed on having the group (directory) name as prefix for the unit names. The description does not reflect that. I kind of don't like that. You need to explain why this is necessary. 

To explain it here again for other readers. In case units are renamed and updated, the controller implementation needs to know what needs to be removed. Because the unit name changed, the unit as it was named before does no longer exist for the controller. Thus the idea was to prefix all units of a group with the group name explicitly, so it can fetch all units having the prefix and do the update.

**Comment by JosephSalisbury** [comment]
Ah, I had forgotten that, I'll update the examples, and put a note in the with the core concepts documentation about this.

**Comment by zeisss** [comment]
Implemented.
